"""Add category_id to product_types

Revision ID: a2c063d703bc
Revises: e36f175cc4b7
Create Date: 2025-04-05 16:05:46.660600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c063d703bc'
down_revision: Union[str, None] = 'e36f175cc4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_types', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product_types', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_types', type_='foreignkey')
    op.drop_column('product_types', 'category_id')
    # ### end Alembic commands ###
