"""added purchase_detail relationships

Revision ID: e36f175cc4b7
Revises: fa6e1f732a9a
Create Date: 2025-02-03 22:49:35.418590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36f175cc4b7'
down_revision: Union[str, None] = 'fa6e1f732a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
